### ISSUE TITLE
4.7.4 kills kodi

### ISSUE THREAD

**Issue by totaltec2014** [cubicle-vdo/xbmc-israel#354]
latest update breaks kodi

**Comment by totaltec2014** [comment]
sorry for lack of info but iw was a rush to find.. basically after the 4.7.4 most kodi windows cannot focus. super favourites also effected a long with many many addons this is RP from iVue

**Comment by avigdork** [comment]
Hi, sorry to hear about that. 
It was seem to work fine on my computer. 
Can you please add a log file?

**Comment by avigdork** [comment]
Try version 4.7.5
Restart Kodi after the update.
If there are still problems, delete addon folder from userdata folder.

**Comment by kostaboxon** [comment]
Serious issue. All 3 linux boxes broken kodi. My mac as well. Uninstalled on mac and installed 4.7.5
See log relating to israel live.
16:36:10 T:4641574912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/Users/helenohehir/Library/Application Support/Kodi/addons/plugin.video.israelive/default.py", line 31, in <module>
                                                remoteSettings = common.GetUpdatedList(remoteSettingsFile, "remoteSettings", remoteSettings, forceUpdate=True)
                                              File "/Users/helenohehir/Library/Application Support/Kodi/addons/plugin.video.israelive/resources/lib/common.py", line 145, in GetUpdatedList
                                                UpdateFile(file, key, remoteSettings=remoteSettings, forceUpdate=forceUpdate)
                                              File "/Users/helenohehir/Library/Application Support/Kodi/addons/plugin.video.israelive/resources/lib/common.py", line 104, in UpdateFile
                                                remoteSettings = json.loads(data)
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/json/__init__.py", line 307, in loads
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/json/decoder.py", line 319, in decode
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/json/decoder.py", line 338, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

**Comment by avigdork** [comment]
I will take a look.
Just a few minutes ago, I uploaded  a new version 4.7.6
(The server was overloaded and the remotSettings file not downloaded)
Pleases try the new version.

**Comment by kostaboxon** [comment]
Wow virtually updated after i wrote.
Updated 4.7.6. Notification loaded guide etc. Rebooted 2 times  addon opens only shows favourites line.
Rest is empty. I will test more and report back.

**Comment by avigdork** [comment]
If you trying it on mac, I know that there is problem to show the list, because of encoding issues (on mac).
If change Kodi language to Hebrew, its fine.
Please send me a log file, so I can see where is the problem. (I don't have a mac)

**Comment by kostaboxon** [comment]
http://goo.gl/TfQdQZ

See log

**Comment by avigdork** [comment]
:+1:
