### ISSUE TITLE
can't download the playlist

### ISSUE THREAD

**Issue by Goga777** [cubicle-vdo/xbmc-israel#443]
with 1.1.5 version of playlist loader I can't load remote playlist http://iptv.slynet.tv/FreeSlyNet.m3u

10:58:02.012 T:2657141664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.playlistLoader/default.py", line 327, in <module>
                                                m3uCategory(url, logos, cache)
                                              File "/storage/.kodi/addons/plugin.video.playlistLoader/default.py", line 121, in m3uCategory
                                                list = common.m3u2list(url, cache)
                                              File "/storage/.kodi/addons/plugin.video.playlistLoader/resources/lib/common.py", line 148, in m3u2list
                                                response = GetList(url, cache)
                                              File "/storage/.kodi/addons/plugin.video.playlistLoader/resources/lib/common.py", line 125, in GetList
                                                response = OpenURL(address)
                                              File "/storage/.kodi/addons/plugin.video.playlistLoader/resources/lib/common.py", line 51, in OpenURL
                                                response = opener.open(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
10:58:02.089 T:3036094464   ERROR: GetDirectory - Error getting plugin://plugin.video.playlistLoader/?cache=0&iconimage&index=0&logos&mode=2&move=0&name=%5bCOLOR%20blue%5d%5b1%5d%5b%2fCOLOR%5d&url=http%3a%2f%2fiptv.slynet.tv%2ffreeslynet.m3u
10:58:02.091 T:3036094464   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.playlistLoader/?cache=0&iconimage&index=0&logos&mode=2&move=0&name=%5bCOLOR%20blue%5d%5b1%5d%5b%2fCOLOR%5d&url=http%3a%2f%2fiptv.slynet.tv%2ffreeslynet.m3u) failed

**Comment by Goga777** [comment]
it was wrong report - the misprinting in url address
